name: Company Analyzer
on:
  workflow_dispatch: {}

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare input (mapuj i czyść CSV)
        run: |
          python prep_input.py input_companies.csv cleaned_input.csv

    - name: Run analyzer (XLSX output)
      run: |
        python analyzer.py input_companies_v2.csv output_companies.xlsx

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: output-companies
          path: output_companies.xlsx
